In [2]:
import pandas as pd
import numpy as np

In [11]:
s = pd.Series([1,3,6,np.nan,4,1]) # similar with 1D numpy
print(s)

0    1.0
1    3.0
2    6.0
3    NaN
4    4.0
5    1.0
dtype: float64


In [12]:
dates = pd.date_range('20160101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=['A','B','C','D'])
print(df['B'])

2016-01-01   -0.602282
2016-01-02    0.889152
2016-01-03   -0.681173
2016-01-04    1.412028
2016-01-05    0.075060
2016-01-06    0.238534
Freq: D, Name: B, dtype: float64


In [13]:
df1 = pd.DataFrame(np.arange(12).reshape((3,4)))
print(df1)

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11


In [14]:
np.arange(12).reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
df1[0]

0    0
1    4
2    8
Name: 0, dtype: int64

In [16]:
df2 = pd.DataFrame({'A' : 1.,
                       'B' : pd.Timestamp('20130102'),
                        'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                        'D' : np.array([3] * 4,dtype='int32'),
                        'E' : pd.Categorical(["test","train","test","train"]),
                        'F' : 'foo'})

In [17]:
print(df2)
print(df2.dtypes)

print(df.index)
print(df.columns)
print(df.values)
print(df.describe())
print(df.T)
print(df.sort_index(axis=1, ascending=False))
print(df.sort_values(by='B'))

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo
A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object
DatetimeIndex(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
               '2016-01-05', '2016-01-06'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='object')
[[-0.88278483 -0.60228245 -0.5501094   0.12576113]
 [-1.00723196  0.88915246  0.35659095 -0.86352935]
 [-0.36970125 -0.68117261  0.93194156 -1.94536231]
 [-0.73324129  1.4120281   1.72059287  0.35032024]
 [ 0.14420406  0.07506035 -0.58788932 -0.5460364 ]
 [-0.84953217  0.23853439  0.59142344 -1.27227515]]
              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.616381  0.221887  0.410425 -0.691854
std    0.431530  0.82198

In [18]:
# 数据选择
dates = pd.date_range('20130101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=['A', 'B', 'C', 'D'])

print(df['A'], df.A)
print(df[0:3], df['20130102':'20130104'])

# select by label: loc
print(df.loc['20130102'])
print(df.loc[:,['A','B']])
print(df.loc['20130102', ['A','B']])

# select by position: iloc
print(df.iloc[3])
print(df.iloc[3, 1])
print(df.iloc[3:5,0:2])
print(df.iloc[[1,2,4],[0,2]])

# mixed selection: ix
print(df.ix[:3, ['A', 'C']])
# Boolean indexing
print(df[df.A > 0])

2013-01-01   -0.716823
2013-01-02   -0.981435
2013-01-03    0.359508
2013-01-04    1.080203
2013-01-05    0.270895
2013-01-06    1.435208
Freq: D, Name: A, dtype: float64 2013-01-01   -0.716823
2013-01-02   -0.981435
2013-01-03    0.359508
2013-01-04    1.080203
2013-01-05    0.270895
2013-01-06    1.435208
Freq: D, Name: A, dtype: float64
                   A         B         C         D
2013-01-01 -0.716823 -0.058999 -1.115310 -0.811255
2013-01-02 -0.981435 -0.059660 -1.496268  0.837364
2013-01-03  0.359508 -0.038713  0.181450 -1.158220                    A         B         C         D
2013-01-02 -0.981435 -0.059660 -1.496268  0.837364
2013-01-03  0.359508 -0.038713  0.181450 -1.158220
2013-01-04  1.080203  1.008137  0.671581 -0.296747
A   -0.981435
B   -0.059660
C   -1.496268
D    0.837364
Name: 2013-01-02 00:00:00, dtype: float64
                   A         B
2013-01-01 -0.716823 -0.058999
2013-01-02 -0.981435 -0.059660
2013-01-03  0.359508 -0.038713
2013-01-04  1.080203  1.0081

/Users/Liu/.pyenv/versions/3.6.3/lib/python3.6/site-packages/ipykernel_launcher.py:20: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
